version: '2'
services:
  db:
    container_name: devops-portfolio-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw 
      MYSQL_DATABASE: flaskDB
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-nw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  web: 
    build: .
    links: 
      - db
    ports:   
      - "5000:5000"
    volumes:
      - ./app:/website
    environment:
      MAIL_SERVER: live.smtp.mailtrap.io
      MAIL_PORT: 587
      MAIL_USERNAME: api
      MAIL_PASSWORD: ee623e05fb4658557164ccceb4b69bd8
    networks:
      - app-nw

  phpmyadmin:
    container_name: devops-portfolio-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA:PORT: 3306
      PMA_USER: example_user
      PMA_PASSWORD: example_password
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      - app-nw

networks:
  app-nw:
    driver: bridge

volumes:
  mysql_data:


