version: '2'
services:
  web: 
    build: .
    ports:   
      - "5000:5000"
    volumes:
      - ./app:/website
    environment:
      MAIL_SERVER: live.smtp.mailtrap.io
      MAIL_PORT: 587
      MAIL_USERNAME: api
      MAIL_PASSWORD: ee623e05fb4658557164ccceb4b69bd8
    networks:
      - app-nw

networks:
  app-nw:
    driver: bridge

volumes:
  mysql_data:
